providers = []

[phases.setup]
nixPkgs = ["nodejs_24", "openssl"]

[phases.install]
cmds = [
  "npm install -g pnpm@9.0.0",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]
